version: '3'
services:
    app:
      container_name: medonist-final
      restart: always
      build: .
      ports:
        - '80:3000'
      environment:
        - NODE_ENV=production
        - MONGODB_HOST_NAME=mongo
        - MONGODB_PORT=27017
        - MONGODB_NAME=medonist
      depends_on:
        - mongo
    mongo:
      image: mongo:4.0.12-xenial
      restart: always
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_DATABASE=medonist
      volumes:
        - ../medonistData:/data/db